name: firebase_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  flex_color_scheme: ^6.0.1
  flutter_bloc: ^8.1.1
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  gap: ^2.0.0
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

  freezed: ^2.2.0
  json_serializable: ^6.5.3
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
