// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPUMjXj4pQfqZvdaohjRU3Cef_79RQ4_E',
    appId: '1:799999070844:web:8ee6d23dfdf9991c972ff9',
    messagingSenderId: '799999070844',
    projectId: 'chatifire',
    authDomain: 'chatifire.firebaseapp.com',
    storageBucket: 'chatifire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LDJPuiOiePQ7TTwrj_QEg0qJavG-ewE',
    appId: '1:799999070844:android:450f0e81e1d495cf972ff9',
    messagingSenderId: '799999070844',
    projectId: 'chatifire',
    storageBucket: 'chatifire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg6mndLy-XIfaxLg8am3Wrj6SIaxPIzvk',
    appId: '1:799999070844:ios:9f30d298db5042b5972ff9',
    messagingSenderId: '799999070844',
    projectId: 'chatifire',
    storageBucket: 'chatifire.appspot.com',
    iosClientId: '799999070844-j5itf3972oqpf3hd0ktesbi167k9lmpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg6mndLy-XIfaxLg8am3Wrj6SIaxPIzvk',
    appId: '1:799999070844:ios:9f30d298db5042b5972ff9',
    messagingSenderId: '799999070844',
    projectId: 'chatifire',
    storageBucket: 'chatifire.appspot.com',
    iosClientId: '799999070844-j5itf3972oqpf3hd0ktesbi167k9lmpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
